source = $HOME/.config/hypr/mocha.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = Pragmasevka Nerd Font


general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    path = ~/.config/backgrounds/mountain-range.jpg
    blur_passes = 2
    color = $base
}

label {
    monitor =
    text = $TIME
    color = $text
    font_size = 90
    font_family = $font
    halign = center
    valign = top
}


image {
  monitor =
  path =
  size = 80
  rounding = 5
  border_color = $accent
  reload_time = 1
  reload_cmd = /home/techgeeks/dotfiles/get_song_image.sh
  position = -100, -300
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] /home/techgeeks/dotfiles/get_song_title.sh
  color = $text
  font_size = 14
  font_family = $font
  position = 950, -300
  halign = left
  valign = center
}

input-field {
    monitor =
    size = 300, 60
    font_family = $font
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $accent
    inner_color = $surface0
    font_color = $text
    fade_on_empty = false
    placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
    hide_input = false
    check_color = $accent
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $yellow
    position = 0, -35
    halign = center
    valign = center
}

#playerctl metadata --format "{{ artist }} - {{ title }}"
