#preload = ~/.config/backgrounds/mountain-range.jpg
#wallpaper = , ~/.config/backgrounds/mountain-range.jpg

wallpaper {
    monitor = 
    path = ~/.config/backgrounds/mountain-range.jpg
    fit_mode = cover
}

splash = false
